### ISSUE TITLE
Move click snooze to config file

### ISSUE THREAD

**Issue by AlexisTEXIER** [Fredrik81/Reboot-Dialog#1]
Hello,

First of all, a big thank you for sharing this tool.

Is it possible to make the sentence "Click Snooze to be reminded in:" just above the choice list configurable?
It would allow me to translate it for my users.

Alexis

**Comment by Fredrik81** [comment]
Will add it in next release tomorrow. 
Also working on multi language config with English being default.

**Comment by Fredrik81** [comment]
Multi language support is now added. You can modify both the default language in the .config file or just add the specific language in the Languages.xml file.
![fr-fr](https://user-images.githubusercontent.com/21292774/53292059-4061ab00-37bd-11e9-9ac1-3b584d35191c.PNG)
