### ISSUE TITLE
Havent been able to trigger dialog in our environment

### ISSUE THREAD

**Issue by dlock-6310** [Fredrik81/Reboot-Dialog#10]
We use SCCM extensively and are trying to get a better grip on the reboot dialogs presented to users for packages and MS updates. This looks like a great tool to do this job, but so far I have not been able to trigger the dialog other than via the "C:\Program Files\RebootDialog\Reboot Dialog.exe" /TestMode option. I can see the "reboot dialog.exe" running OK in task manager, but despite creating "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired" key and installing pkgs requiring reboot via SCCM, I have not been able to get it to trigger the dialog. Machines are Windows 10 v1809. Any suggestions? Thanks

**Comment by Fredrik81** [comment]
I can see the same thing. It works fine in version 1.5.0. Please use that until it's corrected.
https://github.com/Fredrik81/Reboot-Dialog/releases/tag/v1.5.0

**Comment by dlock-6310** [comment]
Thanks Fredrik, that looks good so far.

**Comment by Fredrik81** [comment]
This should be fixed in version 1.5.6:
https://github.com/Fredrik81/Reboot-Dialog/releases/tag/v1.5.6
Feedback is appreciated
