### ISSUE TITLE
Number of times Snoozes can be used

### ISSUE THREAD

**Issue by joshianu** [Fredrik81/Reboot-Dialog#11]
I have a question.
How many times can the snooze option be used?
Is there a way to define it? Or does it depend on SCCM client settings or deployment settings?

My scenario is, we want to limit users to use the snooze option only 3 times and the reboot should be forced after that. How can i achieve this?

Thank you

**Comment by Fredrik81** [comment]
Hello,
Currently the functionality for snooze is based on time not number of times.
You can set multiple options for this as example with the default settings where you start with 4 options for snooze:
15min, 30min, 1 hour and 2 hours
After X amount of days different options will disappear.
So in the latest released version you can also set so after X amount of days where all options will disappear and users will have the reboot dialog in front of any program until they click the reboot.
I hope this covers your needs.

There is no automatic reboot at this time it will be added in later release.
