### ISSUE TITLE
Change Frequency of Reboot Check

### ISSUE THREAD

**Issue by db1982** [Fredrik81/Reboot-Dialog#12]
Love the program, but have a feature request.  It currently checks for necessary updates every 5 minutes.  Can that be configurable via the config file?  I'd like to extend that time if possible.  I've noticed that if updates are being installed and the process takes more than 5 minutes, the Reboot Dialog is being triggered before the update process is complete.  Most users will click the snooze button, but some may actually click reboot while other updates are being installed.  Depending on the number of updates, the process can take quite a while.  I'd like to be able to set it to run every 2-4 hours.  Thanks!

**Comment by Fredrik81** [comment]
Hello,
Thanks for the good feedback!
Interesting. In one of the latest versions there is a check that it should not show dialog if patches are currently being installed. So for me this sounds like a bug request to fix that issue.
Are you running the latest version?

**Comment by db1982** [comment]
That's probably it.  Is it necessary to uninstall the older version prior to installing the update?  Or just run the installer script?

**Comment by Fredrik81** [comment]
The script for installation is just a working example on one way to install it using powershell and scheduled task. It doesn't have version control.
Please check file version of the EXE file you have by just right click on the installed file and properties.

**Comment by db1982** [comment]
If I already have a working installation, is it as simple as copying over the new executable, replacing the older one?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Fredrik81** [comment]
yes that is correct. please check file version that you are using and i will start looking into the issue once i have confirmation. And just to be clear we are talking about windows updates?

**Comment by db1982** [comment]
Yes that is right. I believe we had previously installed version 1.5

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Fredrik81** [comment]
Please test the latest version and if it works close the issue else write back and i will look at it

**Comment by Fredrik81** [comment]
Closing as not feedback after using the latest version
