### ISSUE TITLE
Unable to find the logic how it was searching for pending reboots and Does it create any task scheduler

### ISSUE THREAD

**Issue by rarao90** [Fredrik81/Reboot-Dialog#13]
Am not able to find the logic how it is checking for pending reboots.
1 ) I did not find it in install.ps1 and in the reboot dialog.config file.
2 )Unable to find the logic how it was searching for pending reboots and Does it create any task scheduler

Request you to please let me know where did you defined the logic to check for pending reboots
Also the syntax says 
Disappearing after X amount of days: [Text];[Minutes];[Days Available]
3) i need to make the x amount days to 3 hours

**Comment by bahnjee** [comment]
The EXE is there.  On the main **<>Code** page, click the **releases** link (it currently says **12 releases**).  On that page, scroll down just a little to the **Assets** section.  There is the ZIP you're looking for.

And no, the EXE does not need admin privileges to run.

**Comment by rarao90** [comment]
Am not able to find the logic how it is checking for pending reboots.
I did not find it in install.ps1 and in the reboot dialog.config file.

Request you to please let me know where did you defined the logic to check for pending reboots

**Comment by Fredrik81** [comment]
Hello,
The main logic is inside the exe-file so not really visible.

The logic behind the reboot is using known triggers in the in OS.

Windows update trigger checks registry
- Component Based Servicing (CheckCBS) also check registry
- SCCM trigger checks using WMI
- Boot time trigger checks system ticker

**Comment by rarao90** [comment]
is the main logic was build by using powershell?
is there any possibility to see the logic , i was eager to see the logic

**Comment by Fredrik81** [comment]
the logic is built with C# as this is a "real" program.
If you need powershell for detecting this you can start by looking here:
https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542

As this is not a help forum for powershell i will close the issue with this link.
