### ISSUE TITLE
Add hours config for the snooze options Instead of days

### ISSUE THREAD

**Issue by rarao90** [Fredrik81/Reboot-Dialog#14]
Hi Fredik81

The Tool which you built was really awesome.

Need few more Enhancements to the tool
1) Add Hours for the snooze option instead of days (like 1,2,3,4 days it should be 1 hour, 2 hours etc..)

2) Also the tool should prompt a message for the restart if the hours cycle in the snooze option gets completed

3) it would be great if you can help in changing  this days to hours as it was an urgent requirement for me.

4) is their any possibility see the code that was wrapped in the reboot dialog.exe

**Comment by Fredrik81** [comment]
Added a pre-release as i have not had time to do so much testing on it.
Please try it and give feedback:
https://github.com/Fredrik81/Reboot-Dialog/releases/tag/v1.6.7

**Comment by Fredrik81** [comment]
You can check here for powershell reboot pending:
https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542

**Comment by rarao90** [comment]
Thanks for the Quick Action.

Just curious to know where the system store the snooze values.

Example: If i clicked on Snooze for 15 minutes how does it pop the toast exactly after the 15 mins. where does it store the value.

I have an extra requirement:
I need to pop up the notification by checking the deployment dead line of software updates.
Suppose if the deployment has only two hours left then i need to pop the notification with only two snooze buttons 15 minutes and 30 minutes

Also if you have the idea of getting the snoozed value please share with us.

**Comment by Fredrik81** [comment]
The snooze value is stored in memory. In later release it will be config-file + memory

**Comment by Fredrik81** [comment]
Closed as the new version is now released
