### ISSUE TITLE
Text police and restart button color

### ISSUE THREAD

**Issue by Jacouille91** [Fredrik81/Reboot-Dialog#2]
Hello,
First, nice work !

Second, is it possible for you to add 2 options in the xml file
1) Change the color of the restart button
2) Change the text police

Thx !

**Comment by Fredrik81** [comment]
Thanks!
I will look into the reboot button color and add it in next release.
But what do you mean with text police?

**Comment by AlexisTEXIER** [comment]
Hello,
I think it’s a translation error.
Police is the french word for font.

**Comment by Jacouille91** [comment]
Yes sorry bad translation font = police in french :)

**Comment by Fredrik81** [comment]
I will release a version with option to change color on both buttons during the comming week.
Not the font at this time.

**Comment by Fredrik81** [comment]
This is example of button colors changed:
![image](https://user-images.githubusercontent.com/21292774/57016394-1c39a480-6c1a-11e9-9af9-7e45db05f051.png)
Can be changed in the config file

**Comment by Fredrik81** [comment]
All options for coloring is added but not font type. So i will leave this as complete and if you need something else please add a more specific request.
