### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kyle821** [Fredrik81/Reboot-Dialog#3]
Very cool utility, great work!

Would it be possible to include some kind of log file so that we could track our users' interaction with the reboot dialog? Something like:

[InstallDir]\RebootDialog.log

[DATE] [TIME] Reboot Dialog triggered
[DATE] [TIME] Reason:  Reboot required to install Update [ASDGF8235-DFG3-34JG]
[DATE] [TIME] User selected Snooze for 1 hour
[DATE] [TIME] Reboot Dialog triggered
[DATE] [TIME] Reason:  Reboot required to install Update [ASDGF8235-DFG3-34JG]
[DATE] [TIME] User selected Reboot Now

**Comment by Fredrik81** [comment]
Hello
Thanks for the feedback. This have been requested also from another user so yes I will include it in upcoming version. 
Not sure in what format yet log file, event log etc.

**Comment by Fredrik81** [comment]
Will release this during the comming week.
Loggs will be put in user temp folder.

**Comment by Fredrik81** [comment]
This will be how the logging looks like:
![image](https://user-images.githubusercontent.com/21292774/57015997-062ae480-6c18-11e9-9880-a355314a8970.png)

**Comment by Fredrik81** [comment]
Added in version 1.5.0

**Comment by kyle821** [comment]
Very cool, thanks for your work on this!
