### ISSUE TITLE
Suppress pop-ups until patching has completed

### ISSUE THREAD

**Issue by kjemcn** [Fredrik81/Reboot-Dialog#7]
Is it possible to suppress pop-ups until all patches have been installed. For example, there are 10 patches to install, which may take 30 minutes to install depending on the environment, the reboot dialog pops up immediately when it detects the first reboot required installation. Users who click on Reboot button immediately may end up with multiple reboots in a short period. Ideally, it will wait until all patches have been installed and then start to pop up.

**Comment by AlexisTEXIER** [comment]
I like the idea, but I'd rather see a timer to postpone the first appearance of the pop-up.
With a parameter allowing you to choose the number of minutes to wait.

**Comment by Fredrik81** [comment]
Good feedback!
I will look into this.

lör 15 juni 2019 kl. 11:16 skrev Alexis TEXIER <notifications@github.com>:

**Comment by Fredrik81** [comment]
Solved in v1.5.5. Could still need some testing

**Comment by kjemcn** [comment]
Thanks for looking into it! I've downloaded the new version and tested a few rounds (using SCCM). However the reboot dialog never popped up again in all tests. Could you please take a look when you get a chance?

**Comment by Fredrik81** [comment]
This is solved with version v1.5.6
Was a bug with suppressing the popup if updates are running.
