### ISSUE TITLE
Sooze button still shows after reminders are exhausted 

### ISSUE THREAD

**Issue by gustavonm** [Fredrik81/Reboot-Dialog#8]
**Describe the bug**
Sooze button still shows after reminders are exhausted, remider options drop down menu shows empty. Clicking on Snooze sometimes crash Rebootdialog.exe 

**To Reproduce**
1. Configure reminders to expire in 1 and 2 days:
            <string>15min;15;2</string>
            <string>30min;30;2</string>
            <string>1hour;60;2</string>
            <string>2hours;120;1</string>
            <string>4hours;240;1</string>
2. After 2 dyas, all option will be gone, but Snooze button still shows.

**Expected behavior**
Snooze Button should disapear when there is no reminders options. 
Even better, reminders drop down menu should disapper, leavieng the option only to reboot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48105377/61117119-2ab40000-a496-11e9-8799-278cd84710df.png)

![image](https://user-images.githubusercontent.com/48105377/61117158-3dc6d000-a496-11e9-83d2-ea27644153fb.png)

**Desktop (please complete the following information):**
 - OS: Windows 1809

**Comment by schiffne** [comment]
We do see the same problem, wanted to report it already a while back. BTW can you share the code sources here as well, so we can further develop it with you?

MANY THANKS!

**Comment by Fredrik81** [comment]
Hello,
Thanks for reporting this! Never tested it that way but easy fix. Will make sure it's solved until next release.
Have a few things being worked on from the other requests but it's a but slow during summer time B-)

**Comment by Fredrik81** [comment]
Solved in v1.5.5
