### ISSUE TITLE
Option to supress the pop-up

### ISSUE THREAD

**Issue by snruebes** [Fredrik81/Reboot-Dialog#9]
**Is your feature request related to a problem? Please describe.**
Could you add an option to the XML to suppress the pop-up as long as the  the presentationsettings.exe is running. Users are usually enabling it while the give a Powerpoint presentation - it would be very disturbing when this pop-up kicks in just in this moment.

**Describe the solution you'd like**
Don't show the RebootDialog Window as long as presentationsettings.exe task is running

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Fredrik81** [comment]
First thanks for the idea!
I have been testing this at home and at work. I don't have the presentationsettings.exe running while presenting in PowerPoint using O365 at home and O365 ProPlus at work.
But I’m working on something else to suppress the dialog when fullscreen program is running. Hope to have it finished soon.

**Comment by Fredrik81** [comment]
A small update on this. It's a bit tricky to get this right but later builds on windows 10 have some good api's for this so will see if i can use them.

**Comment by Fredrik81** [comment]
This is now added in pre-release version v1.7.0
Please test it out and give feedback!
https://github.com/Fredrik81/Reboot-Dialog/releases/tag/v1.7.0
